### PR TITLE
make it work in text and voice channels

### LINKED ISSUE #3: Channel Copy Link button doesn't work as intended
~~As of commit 5188204eccb6de60f491d72ffb2a1453849cc5df the features added in #1 no longer work.~~

Edit: #1 never worked

### PR DESCRIPTION
**Pull request by SebbyLaw**
Tested and working with text and voice channels.

Can't figure out how to properly inject into `ChannelListThreadContextMenu`. Nothing seems to happen ever, and the module can't be fetched.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -26,56 +26,77 @@ module.exports = class ViewRaw extends Plugin {
 				el.props.children = [el.props.children];
 			el.props.children.forEach(x => {
 				if (!x || !x.props) return;
-				if (x.props.id === 'copy-link') {
+				if (x.props.id && x.props.id.endsWith('copy-link')) {
```
Comment (asportnoy) [inline index.js]:
```suggestion
				if (x.props.id?.endsWith('copy-link')) {
```

**Review by asportnoy — CHANGES_REQUESTED** [review]

**Review by asportnoy — APPROVED** [review]
